.gitignore, nuxt.config.ts, package.json, src/index.d.ts, src/server/plugins/storage-config.ts, src/server/utils/storage.ts, yarn.lock
=> feat(s3-integration): Use S3 storage in prod and local in dev mode.

src/assets/css/additional-styles/utility-patterns.css, src/components/abstract/ConfirmationBox.vue, src/components/abstract/OptionsSelectorDropdown.vue, src/components/admin/integration/hooks/Form.vue, src/components/admin/postings/EmptyState.vue, src/components/admin/settings/general/Update.vue, src/pages/admin/postings/edit.vue, src/pages/postings/[id].vue
=> Generalised specific type of button

Dockerfile
Optimize docker build time using cache mount
fixes: #58
=> Optimize docker build time

.github/dependabot.yml
Configure dependabot to manage npm dependencies upgrades
fixes: #38
=> Configure dependabot to manage npm dependencies upgrades

.github/dependabot.yml
Include labels on dependabot pull_requests
Include labels on dependabot pull_requests
[Attach screenshots or videos demonstrating the new feature in action.]
Loom Video: [loom](https://www.loom.com/)
=> Include labels on dependabot pull_requests

.github/dependabot.yml
as we have discussed on https://github.com/profilecity/vidur/pull/57
configure dependabot to keep update dockerfile
[Attach screenshots or videos demonstrating the new feature in action.]
Loom Video: [loom](https://www.loom.com/)
=> chore: configure dependabot to keep update dockerfile

src/utils/general.ts
In this PR, I have fixedt type error for date format options.
[Attach screenshots or videos demonstrating the new feature in action.]
Loom Video: [loom](https://www.loom.com/)
=> Fix: Type error for date format options

docs/README.md
[A brief overview of the feature being added. Explain the functionality and its intended purpose.]
Fix: Broken link of website and discord in README.md
[Attach screenshots or videos demonstrating the new feature in action.]
Loom Video: [loom](https://www.loom.com/)
=> Fix: Broken link of website and discord

src/components/admin/integration/hooks/Form.vue
=> Fix: misspelled grammar

.gitignore, .husky/pre-commit, .prettierignore, package.json, yarn.lock
This PR configure prettier code formatter with pre-commit hooks
fixes: #94
=> Configure prettier and husky to enhance codebase

.dockerignore
=> Exclude some file to optimise docker build performance

nuxt.config.ts, src/components/admin/Sidebar.vue
=> Create runtime config for extra options

.husky/post-commit, .husky/pre-commit, .prettierignore, .prettierrc, .vscode/settings.json, package.json, yarn.lock
- This https://github.com/profilecity/vidur/commit/f98270afd04dfea3562cb3c180db0b2e7ad4094c commit reffers to config of prettier and 
- This https://github.com/profilecity/vidur/commit/a5e414f9ef54e2a6d674b4a89074e173ae0e6472 commit reffers to latest code style depend on `.prettierrc` file.
- fixes: #94 
Also, now it would format only edited file if you run `yarn format` otherwise it won't, this is why i formatted codebase in this commit https://github.com/profilecity/vidur/commit/a5e414f9ef54e2a6d674b4a89074e173ae0e6472
=> Enhance code style with prettier and husky

.dockerignore
Exclude more file to optimise docker build process because we have done some recent work
=> Optimise docker build process

server/api/posting/index.delete.ts, server/api/posting/index.get.ts, server/api/posting/index.post.ts, server/api/posting/index.put.ts, server/api/postings/index.get.ts, server/api/postings/lite.get.ts, server/api/public/posting.get.ts, server/api/public/postings.get.ts, server/utils/tasks/seed-cache.ts
Postings will now be served from cache. TotalApplicants will still require db lookup.
Resolves #113
=> perf(posting): serve postings from cache

.github/workflows/lint.yml
It will install dependencies from lockfile without updating it (faster)
=> Install dependencies from `lockfile`

app/pages/index.vue, nuxt.config.ts
`feat: update URL structure for profile redirection`
This update changes the URL structure from `https://vidurjobs.xyz` to `https://profilecity.xyz/vidur`. The purpose of this change is to improve the overall user experience by redirecting to the new profile page with a more relevant domain name. It ensures that users are routed to the correct profile page without breaking the existing functionality.
=> chore: update URL from vidurjobs.xyz to profilecity.xyz/vidur

app/components/SiteHeader.vue
Open all three links on new tab to improve UX
=> feat: Open links on new tab to improve UX

app/components/admin/ApplicationRow.vue
feat: Verify that the resume exists for all applicants
fixes: #173
=> feat: Verify that the resume exists for all applicants

nuxt.config.ts
Update vidur version in plateform side navbar.
fixes #170
=> UI: update vidur version in side navbar

server/db/migrations/0001_mysterious_green_goblin.sql, server/db/migrations/meta/0001_snapshot.json, server/db/migrations/meta/_journal.json, server/db/schema.ts, shared/employment-types.ts, shared/schemas/posting.ts, shared/types/posting-types.ts
Create SEO fields for job posting
fixes: #134
=> feat(db): Create SEO fields for job posting

server/utils/db.ts
=> fix(db): ensure application fails if db connection not established

nuxt.config.ts
see- https://nodejs.org/docs/latest-v22.x/api/esm.html#json-modules
=> json module is stable now

app/components/admin/PostingCard.vue, app/utils/general.ts, package.json, yarn.lock
=> feat(ui): display early postings which will expire
